### ISSUE TITLE
We shouldn't use :not as much.

### ISSUE THREAD

**Issue by jdevalk** [WordPress/twentynineteen#528]
Currently, we have a lot of CSS that is very non-performant, but also not very readable. Specifically, I think we shouldn't use `:not` as much, in things like:

```css
.entry-content .wp-block-separator:not(.is-style-dots),
.entry-content hr:not(.is-style-dots) {
  background-color: #767676;
  border: 0;
  height: 2px;
}

.entry-content .wp-block-separator:not(.is-style-wide):not(.is-style-dots),
.entry-content hr:not(.is-style-wide):not(.is-style-dots) {
  max-width: 2.25em;
}
```

It should be the other way round:

`.wp-block-separator` should have a `max-width`, so `.wp-block-separator.is-style-wide` etc can override that with its own `max-width`, that would make the CSS _much_ faster to parse for both humans and computer readers.
